import fastapi
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import numpy as np
import cv2
import io
import base64
from fpdf import FPDF
import datetime

# Setup FastAPI App
app = FastAPI(title="Skin Cancer AI Backend")

# Allow all CORS for development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 1. MODEL SETUP ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = models.resnet18()
model.fc = nn.Linear(model.fc.in_features, 2)
# Load safely for both CPU and GPU depending on system execution
try:
    model.load_state_dict(torch.load('skin_model.pth', map_location=device))
except FileNotFoundError:
    print("Warning: skin_model.pth not found. Please ensure it is in the same directory.")
model.to(device).eval()

# --- 2. GRAD-CAM & DETECTION ENGINES ---
class GradCAM:
    def __init__(self, model, target_layer):
        self.model, self.target_layer = model, target_layer
        self.gradients, self.activations = None, None
        def save_gradient(module, grad_input, grad_output): self.gradients = grad_output[0]
        def save_activation(module, input, output): self.activations = output
        self.target_layer.register_forward_hook(save_activation)
        self.target_layer.register_full_backward_hook(save_gradient)

    def generate(self, input_tensor, class_idx):
        output = self.model(input_tensor)
        self.model.zero_grad()
        output[0, class_idx].backward()
        weights = torch.mean(self.gradients, dim=(2, 3), keepdim=True)
        cam = torch.sum(weights * self.activations, dim=1).squeeze().detach().cpu().numpy()
        cam = np.maximum(cam, 0)
        cam = cv2.resize(cam, (224, 224))
        if cam.max() - cam.min() == 0:
            return cam
        return (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)

def detect_moles(image_pil):
    img = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2BGR)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    moles = []
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        if w > 25 and h > 25: # Filtering noise
            padding = 15
            crop = img[max(0, y-padding):y+h+padding, max(0, x-padding):x+w+padding]
            moles.append({'img': crop, 'box': (x, y, w, h)})
    return moles

# --- 3. PDF GENERATOR ---
def create_pdf_report(result, confidence, original_img, heatmap_img):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", 'B', 20)
    pdf.cell(0, 10, text="Medical AI Analysis Report", align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", size=10)
    pdf.cell(0, 10, text=f"Date: {datetime.date.today()}", align='C', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    pdf.set_font("helvetica", 'B', 14)
    pdf.cell(0, 10, text="1. Analysis Results", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", size=12)
    pdf.cell(0, 10, text=f"Detected Category: {result}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, text=f"AI Confidence Score: {confidence:.2f}%", new_x="LMARGIN", new_y="NEXT")
    
    original_img.save("temp_orig.png")
    heatmap_img.save("temp_heat.png")
    pdf.image("temp_orig.png", x=10, y=80, w=90)
    pdf.image("temp_heat.png", x=110, y=80, w=90)
    
    pdf.set_y(-30)
    pdf.set_font("helvetica", 'I', 8)
    pdf.multi_cell(0, 5, text="DISCLAIMER: This report is generated by an AI model for informational use only. Consult a dermatologist for medical diagnosis.")
    return bytes(pdf.output())

# Helper to encode image to base64
def pil_to_base64(img: Image.Image) -> str:
    buffered = io.BytesIO()
    img.save(buffered, format="PNG")
    return base64.b64encode(buffered.getvalue()).decode('utf-8')

# --- 4. API ENDPOINTS ---
@app.post("/api/analyze")
async def analyze_image(file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents)).convert('RGB')
    
    # 1. Prepare image for ResNet
    transform = transforms.Compose([
        transforms.Resize((224, 224)), 
        transforms.ToTensor(), 
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    img_tensor = transform(image).unsqueeze(0).to(device)
    img_tensor.requires_grad = True
    
    # 2. Run model prediction
    output = model(img_tensor)
    conf, pred = torch.max(torch.nn.functional.softmax(output, dim=1), 1)
    
    # 3. Generate Grad-CAM Heatmap
    cam_engine = GradCAM(model, model.layer4[1].conv2)
    mask = cam_engine.generate(img_tensor, pred.item())
    heatmap = cv2.applyColorMap(np.uint8(255 * mask), cv2.COLORMAP_JET)
    overlay = cv2.addWeighted(np.array(image.resize((224, 224))), 0.6, cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB), 0.4, 0)
    overlay_pil = Image.fromarray(overlay)
    
    # 4. Gather results
    res_text = ['Melanoma', 'NotMelanoma'][pred.item()]
    confidence_val = conf.item() * 100
    
    # 5. Generate PDF Document Base64
    pdf_bytes = create_pdf_report(res_text, confidence_val, image.resize((224, 224)), overlay_pil)
    pdf_b64 = base64.b64encode(pdf_bytes).decode('utf-8')
    
    return {
        "result": res_text,
        "confidence": confidence_val,
        "heatmap": f"data:image/png;base64,{pil_to_base64(overlay_pil)}",
        "original": f"data:image/png;base64,{pil_to_base64(image.resize((224, 224)))}",
        "pdf": pdf_b64
    }

@app.post("/api/detect")
async def detect_multi(file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents)).convert('RGB')
    
    moles = detect_moles(image)
    results = []
    
    t = transforms.Compose([
        transforms.Resize((224, 224)), 
        transforms.ToTensor(), 
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    
    for m in moles:
        crop_pil = Image.fromarray(cv2.cvtColor(m['img'], cv2.COLOR_BGR2RGB))
        with torch.no_grad():
            out = model(t(crop_pil).unsqueeze(0).to(device))
            conf, pred = torch.max(torch.nn.functional.softmax(out, dim=1), 1)
            res = ['Melanoma', 'NotMelanoma'][pred.item()]
            
        results.append({
            "result": res,
            "confidence": conf.item() * 100,
            "image": f"data:image/png;base64,{pil_to_base64(crop_pil)}",
            "box": m['box']
        })
        
    return {
        "count": len(results),
        "spots": results,
        "original": f"data:image/png;base64,{pil_to_base64(image.resize((224, 224)))}"
    }

# Mount static files at the root
app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
